# Perfil LOCAL — sobreescribe application.yml para desarrollo en máquina personal.
# NO incluir en imagen Docker ni en ECS Task Definition.
spring:
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    password: StaySync@Rabbit#2024$Pass

jwt:
  secret: StaySyncJWT_SuperSecretKey_Min256Bits_2024!XyZ#AbC
